version: "3.4"

services:
  es:
    image: elasticsearch:7.9.0
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./containers/es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
